pipeline {
    agent any

    environment {
        S3_BUCKET = 'my-s3-bucket-for-jenkins-pipeline-setup'
        S3_KEY = 'my-app.zip'
        ENVIRONMENT_NAME = 'Sample-beanstalk-env-env'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ManojKamatam/Beanstalk_Deployemt.git', branch: 'main'
            }
        }
        
        stage('Upload to S3') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials-id'
                ]]) {
                    sh "aws s3 cp application.zip s3://${S3_BUCKET}/${S3_KEY}"
                }
            }
        }

        stage('Deploy with Terraform') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials-id'
                ]]) {
                    dir('terraform') {
                        sh 'terraform init'
                        sh """
                            terraform apply -auto-approve \
                            -var 's3_bucket=${S3_BUCKET}' \
                            -var 's3_key=${S3_KEY}'\
                            -var 'environment_name=${ENVIRONMENT_NAME}'
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Deployment process completed.'
        }
    }
}
