pipeline {
    agent any

    environment {
        S3_BUCKET = 'my-s3-bucket-for-jenkins-pipeline-setup'  // Replace with your actual S3 bucket name
        S3_KEY = 'my-app.zip'  // Replace with the actual S3 key you want to use
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ManojKamatam/Beanstalk_Deployemt.git', branch: 'main'
            }
        }

        stage('Upload to S3') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'AKIA5CBDRLE2P27OTD43'
                ]]) {
                    sh "aws s3 cp app.zip s3://${S3_BUCKET}/${S3_KEY}"
                }
            }
        }

        stage('Deploy with Terraform') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'AKIA5CBDRLE2P27OTD43'
                ]]) {
                    dir('terraform') {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Deployment process completed.'
        }
    }
}
